.TH FileFinder "1" "filefinder"
.SH NAME
filefinder \- advanced search tool.
.SH SYNOPSIS
.B filefinder
.RI [\fBoptions\fR]
[[\fILOCATION\fR] ...]
.SH DESCRIPTION
.B File Finder
is an advanced file search tool and Nautilus extension.
There is async threaded multiple location searching with file masking, MIME types, modified dates, file sizes, text and binary search patterns.
The search results can be sorted by attributes and processed with common actions like opening with a default application, containing folder, copy/move to destination folder or trashing selection.
.SH OPTIONS
.TP
.BR \-\-help
Show the help and exit.
.TP
.BR \-\-version
Show version number and exit.
.TP
.BR \-\-license
Show license and exit.
.TP
.BR \-\-debug
Print debug messages.
.TP
.BR \fILOCATION\fR
Set the \fILOCATION\fR to the search query.
\fILOCATION\fR(s) can be a filesystem directory or a file.
Multiple \fILOCATION\fR(s) could be separated by spacebar.
.SH USAGE
.TP
* Open curent directory to search:
filefider .
.TP
* Open home directory and 2 files to search:
filefinder ~ ~/file1.html ~/file2.html
